import GetButton from "@/components/api/GetButton";
import Status from "@/components/api/Status";

const apiData = [
  {
    category: "ai",
    endpoints: [
      {
        id: 1,
        name: "AI",
        method: <GetButton />,
        description: "Tanya apa aja ke AI",
        queryParameter: "text",
        status: <Status type="error" />,
        link: "/api/openai?text=halo",
      },
      {
        id: 2,
        name: "Dalle",
        method: <GetButton />,
        description: "Buat gambar dari Text dengan AI",
        queryParameter: "text",
        status: <Status type="error" />,
        link: "/api/dalle?text=cat",
      },
    ],
  },
  {
    category: "downloader",
    endpoints: [
      {
        id: 1,
        name: "Tiktok",
        method: <GetButton />,
        description: "Tiktok downloader no watermark",
        queryParameter: "url",
        status: <Status />,
        link: "/api/tiktok?url=",
      },
      {
        id: 2,
        name: "Youtube Audio",
        method: <GetButton />,
        description: "Download Mp3",
        queryParameter: "url",
        status: <Status />,
        link: "/api/ytaudio?url=",
      },
      {
        id: 3,
        name: "Youtube Play",
        method: <GetButton />,
        description: "Youtube Play",
        queryParameter: "query",
        status: <Status />,
        link: "/api/play?query=",
      },
      {
        id: 4,
        name: "Youtube Search",
        method: <GetButton />,
        description: "Youtube Search",
        queryParameter: "query",
        status: <Status />,
        link: "/api/ytsearch?query=dj%20bangka%20dada",
      },
      {
        id: 5,
        name: "Youtube Video",
        method: <GetButton />,
        description: "Download MP4",
        queryParameter: "url",
        status: <Status />,
        link: "/api/ytvideo?url=",
      },
      {
        id: 6,
        name: "Mediafire",
        method: <GetButton />,
        description: "Download file Mediafire",
        queryParameter: "url",
        status: <Status />,
        link: "/api/mediafire?url=https://www.mediafire.com/file/nucuho4oi9bax6o/hotspot.zip/file",
      },
      {
        id: 7,
        name: "Pinterest",
        method: <GetButton />,
        description: "Download MP4 Pinterest",
        queryParameter: "url",
        status: <Status />,
        link: "/api/pinterest?url=",
      },
      {
        id: 8,
        name: "Facebook",
        method: <GetButton />,
        description: "Download Video Facebook",
        queryParameter: "url",
        status: <Status />,
        link: "/api/facebook?url=",
      },
    ],
  },
  {
    category: "islami",
    endpoints: [
      {
        id: 1,
        name: "Audio Ayat",
        method: <GetButton />,
        description: "Get audio ayat from surah",
        queryParameter: "id&ayat",
        status: <Status />,
        link: "/api/islamic/ayat-audio?id=36&ayat=",
      },
      {
        id: 2,
        name: "Audio Surah",
        method: <GetButton />,
        description: "Get audio surah from Al Quran",
        queryParameter: "id/surah",
        status: <Status />,
        link: "/api/islamic/surah-audio?id=",
      },
      {
        id: 3,
        name: "Doa Doa",
        method: <GetButton />,
        description: "Get daily prayers",
        queryParameter: "id/query/pics",
        status: <Status />,
        link: "/api/islamic/doa?query=makan",
      },
      {
        id: 4,
        name: "Ayat",
        method: <GetButton />,
        description: "Get ayat from surah",
        queryParameter: "-",
        status: <Status />,
        link: "/api/islamic/quran/1/1",
      },
      {
        id: 5,
        name: "Ayat 2",
        method: <GetButton />,
        description: "Get ayat from surah",
        queryParameter: "-",
        status: <Status />,
        link: "/api/islamic/quran/2/190-192",
      },
      {
        id: 6,
        name: "Jadwal Sholat",
        method: <GetButton />,
        description: "Get jadwal sholat by nama kota",
        queryParameter: "kota",
        status: <Status />,
        link: "/api/islamic/jadwal-sholat?kota=cirebon",
      },
      {
        id: 7,
        name: "List Surah",
        method: <GetButton />,
        description: "Show all surah in Al Quran",
        queryParameter: "-",
        status: <Status />,
        link: "/api/islamic/quran",
      },
      {
        id: 8,
        name: "Surah",
        method: <GetButton />,
        description: "Get surah from Al Quran",
        queryParameter: "-",
        status: <Status />,
        link: "/api/islamic/quran/36",
      },
      {
        id: 9,
        name: "Tafsir Ayat",
        method: <GetButton />,
        description: "Get Tafsir from ayat",
        queryParameter: "-",
        status: <Status />,
        link: "/api/islamic/tafsir-ayat/1/1",
      },
      {
        id: 10,
        name: "List Kota",
        method: <GetButton />,
        description: "Get a list of cities for prayer times ",
        queryParameter: "-",
        status: <Status />,
        link: "/api/islamic/list-kota",
      },
      {
        id: 11,
        name: "Jadwal Sholat2",
        method: <GetButton />,
        description: "Get jadwal sholat by nama kota",
        queryParameter: "kota",
        status: <Status />,
        link: "/api/islamic/jadwal-sholat2?kota=cirebon",
      },
      {
        id: 11,
        name: "Kisah Nabi",
        method: <GetButton />,
        description: "Get the story of the prophet",
        queryParameter: "query/pics",
        status: <Status />,
        link: "/api/islamic/kisah-nabi?query=adam",
      },
    ],
  },
  {
    category: "entertainment",
    endpoints: [
      {
        id: 1,
        name: "Siapakah Aku",
        method: <GetButton />,
        description: "Siapakah Aku",
        queryParameter: "pics/index",
        status: <Status />,
        link: "/api/game/siapakah-aku?pics",
      },
      {
        id: 2,
        name: "Tebak Bendera",
        method: <GetButton />,
        description: "Tebak Bendera",
        queryParameter: "pics",
        status: <Status />,
        link: "/api/game/tebak-bendera?pics",
      },
      {
        id: 3,
        name: "Tebak Gambar",
        method: <GetButton />,
        description: "Tebak Gambar",
        queryParameter: "pics/index",
        status: <Status />,
        link: "/api/game/tebak-gambar?pics",
      },
      {
        id: 4,
        name: "Tebak Lagu",
        method: <GetButton />,
        description: "Tebak Lagu",
        queryParameter: "pics",
        status: <Status />,
        link: "/api/game/tebak-lagu?pics",
      },
    ],
  },
  {
    category: "randomImage",
    endpoints: [
      {
        id: 1,
        name: "Stiker Meme",
        method: <GetButton />,
        description: "Get Stiker Meme",
        queryParameter: "-",
        status: <Status />,
        link: "/api/other?query=sticker",
      },
      {
        id: 2,
        name: "waifu",
        method: <GetButton />,
        description: "Get Waifu Iamge",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/waifu",
      },
      {
        id: 3,
        name: "neko",
        method: <GetButton />,
        description: "Get Neko Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/neko",
      },
      {
        id: 3,
        name: "shinobu",
        method: <GetButton />,
        description: "Get Shinobu Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/shinobu",
      },
      {
        id: 4,
        name: "megumin",
        method: <GetButton />,
        description: "Get Megumin Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/megumin",
      },
      {
        id: 5,
        name: "bully",
        method: <GetButton />,
        description: "Get Bully Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/bully",
      },
      {
        id: 6,
        name: "cuddle",
        method: <GetButton />,
        description: "Get Cuddle Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/cuddle",
      },
      {
        id: 7,
        name: "cry",
        method: <GetButton />,
        description: "Get Cry Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/cry",
      },
      {
        id: 8,
        name: "hug",
        method: <GetButton />,
        description: "Get Hug Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/hug",
      },
      {
        id: 9,
        name: "awoo",
        method: <GetButton />,
        description: "Get Awoo Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/awoo",
      },
      {
        id: 10,
        name: "kiss",
        method: <GetButton />,
        description: "Get Kiss Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/kiss",
      },
      {
        id: 11,
        name: "lick",
        method: <GetButton />,
        description: "Get Lick Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/lick",
      },
      {
        id: 12,
        name: "pat",
        method: <GetButton />,
        description: "Get Pat Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/pat",
      },
      {
        id: 13,
        name: "smug",
        method: <GetButton />,
        description: "Get Smug Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/smug",
      },
      {
        id: 14,
        name: "bonk",
        method: <GetButton />,
        description: "Get Bonk Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/bonk",
      },
      {
        id: 15,
        name: "yeet",
        method: <GetButton />,
        description: "Get Yeet Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/yeet",
      },
      {
        id: 16,
        name: "blush",
        method: <GetButton />,
        description: "Get Blush Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/blush",
      },
      {
        id: 17,
        name: "smile",
        method: <GetButton />,
        description: "Get Smile Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/smile",
      },
      {
        id: 18,
        name: "wave",
        method: <GetButton />,
        description: "Get Wave Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/wave",
      },
      {
        id: 19,
        name: "highfive",
        method: <GetButton />,
        description: "Get Highfive Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/highfive",
      },
      {
        id: 20,
        name: "handhold",
        method: <GetButton />,
        description: "Get Handhold Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/handhold",
      },
      {
        id: 21,
        name: "nom",
        method: <GetButton />,
        description: "Get Nom Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/nom",
      },
      {
        id: 22,
        name: "bite",
        method: <GetButton />,
        description: "Get Bite Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/bite",
      },
      {
        id: 23,
        name: "glomp",
        method: <GetButton />,
        description: "Get Glomp Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/glomp",
      },
      {
        id: 24,
        name: "slap",
        method: <GetButton />,
        description: "Get Slap Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/slap",
      },
      {
        id: 25,
        name: "kill",
        method: <GetButton />,
        description: "Get Kill Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/kill",
      },
      {
        id: 26,
        name: "kick",
        method: <GetButton />,
        description: "Get Kick Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/kick",
      },
      {
        id: 27,
        name: "happy",
        method: <GetButton />,
        description: "Get Happy Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/happy",
      },
      {
        id: 28,
        name: "wink",
        method: <GetButton />,
        description: "Get Wink Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/wink",
      },
      {
        id: 29,
        name: "poke",
        method: <GetButton />,
        description: "Get Poke Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/poke",
      },
      {
        id: 30,
        name: "dance",
        method: <GetButton />,
        description: "Get Dance Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/dance",
      },
      {
        id: 31,
        name: "cringe",
        method: <GetButton />,
        description: "Get Cringe Image",
        queryParameter: "-",
        status: <Status />,
        link: "/api/random/sfw/cringe",
      },
      {
        id: 32,
        name: "Nijika",
        method: <GetButton />,
        description: "Get Nijika Image",
        queryParameter: "name",
        status: <Status />,
        link: "/api/anime?name=nijika",
      },
      {
        id: 33,
        name: "Ikuyo",
        method: <GetButton />,
        description: "Get IKuyo Image",
        queryParameter: "name",
        status: <Status />,
        link: "/api/anime?name=ikuyo",
      },
      {
        id: 34,
        name: "Elaina",
        method: <GetButton />,
        description: "Get Elaina Image",
        queryParameter: "name",
        status: <Status />,
        link: "/api/anime?name=elaina",
      },
      {
        id: 35,
        name: "Sasuke",
        method: <GetButton />,
        description: "Get Sasuke Image",
        queryParameter: "name",
        status: <Status />,
        link: "/api/anime?name=sasuke",
      },
      {
        id: 36,
        name: "Loli",
        method: <GetButton />,
        description: "Get Loli Image",
        queryParameter: "name",
        status: <Status />,
        link: "/api/anime?name=loli",
      },
      {
        id: 37,
        name: "Walpaper Anime",
        method: <GetButton />,
        description: "Get Walpaper Anime Image",
        queryParameter: "name",
        status: <Status />,
        link: "/api/anime?name=wallnime",
      },
    ],
  },
  {
    category: "news",
    endpoints: [
      {
        id: 1,
        name: "Info Gempa",
        method: <GetButton />,
        description: "Info gemmpa terbaru",
        queryParameter: "-",
        status: <Status />,
        link: "/api/news/gempa",
      },
      {
        id: 2,
        name: "Info Gempa 2",
        method: <GetButton />,
        description: "Info gemmpa terbaru",
        queryParameter: "-",
        status: <Status />,
        link: "/api/news/gempa2",
      },
      {
        id: 3,
        name: "CNBC",
        method: <GetButton />,
        description: "Info CNBC terbaru",
        queryParameter: "category",
        status: <Status />,
        link: "/api/news/cnbc",
      },
      {
        id: 4,
        name: "Kompas",
        method: <GetButton />,
        description: "Info Kompas terbaru",
        queryParameter: "-",
        status: <Status />,
        link: "/api/news/kompas",
      },
    ],
  },
];

export default apiData;
