import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import AddData from "@/components/tools/addData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nanda Ilham Buqori",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AddData apiUrl="https://counter.nandaxy.repl.co/add" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
